# shellcheck shell=bash
# helpers/state.sh — read DOTS machine state / logs (non-mutating)
#
# Requires: DIR (repo root)

dots_version() {
	local f="${DIR}/VERSION"
	if [[ -f ${f} ]]; then
		tr -d '[:space:]' <"${f}"
		return 0
	fi
	printf 'unknown\n'
}

dots_state_dir() {
	printf '%s\n' "${HOME}/.local/state/dots"
}

dots_log_dir() {
	printf '%s\n' "$(dots_state_dir)/logs"
}

dots_config_dir() {
	printf '%s\n' "${HOME}/.config/dots"
}

dots_user_profiles_dir() {
	printf '%s\n' "$(dots_config_dir)/profiles"
}

dots_active_profile_file() {
	printf '%s\n' "$(dots_config_dir)/active-profile"
}

dots_runtime_env_file() {
	printf '%s\n' "$(dots_config_dir)/runtime.env"
}

dots_user_models_file() {
	printf '%s\n' "$(dots_config_dir)/models.toml"
}

# Load DOTS_PROFILE / DOTS_PROFILE_FILE from active-profile if present.
#
# Active components for READ-ONLY discovery (packages status, ./dots components):
#   Prefer DOTS_ACTIVE_COMPONENTS when present; else map from DOTS_LAST_WITH_INFO
#   so older active-profile files work without re-bootstrap.
#   Both are INFORMATIONAL only — not AI / mutating-setup consent.
#   Mutating setup still requires profile `with` / `./setup.sh --with` this run.
dots_state_load_active() {
	DOTS_ACTIVE_PROFILE=""
	DOTS_ACTIVE_PROFILE_FILE=""
	DOTS_ACTIVE_COMPONENTS=""
	DOTS_ACTIVE_PACKAGE_GROUPS=""
	local f
	f="$(dots_active_profile_file)"
	[[ -f ${f} ]] || return 1
	# shellcheck disable=SC1090
	source "${f}"
	DOTS_ACTIVE_PROFILE="${DOTS_PROFILE:-}"
	DOTS_ACTIVE_PROFILE_FILE="${DOTS_PROFILE_FILE:-}"
	DOTS_ACTIVE_PACKAGE_GROUPS="${DOTS_PACKAGE_GROUPS:-}"
	# BC: LAST_WITH_INFO-only files → expose as ACTIVE_COMPONENTS for readers.
	if [[ -z ${DOTS_ACTIVE_COMPONENTS:-} && -n ${DOTS_LAST_WITH_INFO:-} ]]; then
		DOTS_ACTIVE_COMPONENTS="${DOTS_LAST_WITH_INFO}"
	fi
	# Prefer explicit ACTIVE_COMPONENTS if both exist; keep LAST_WITH_INFO as written.
	if [[ -z ${DOTS_LAST_WITH_INFO:-} && -n ${DOTS_ACTIVE_COMPONENTS:-} ]]; then
		DOTS_LAST_WITH_INFO="${DOTS_ACTIVE_COMPONENTS}"
	fi
	return 0
}

dots_state_ensure_log_dir() {
	mkdir -p "$(dots_log_dir)" 2>/dev/null || true
}

# New log path for a run.
dots_state_new_log() {
	local stamp name="${1:-dots}"
	stamp="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo now)"
	dots_state_ensure_log_dir
	printf '%s/%s-%s.log\n' "$(dots_log_dir)" "${name}" "${stamp}"
}

# Pure-Bash write of a simple user profile TOML (no Python required).
# Args: dest name extends description multiplexer with_csv without_csv pkg_add_csv
dots_write_profile_toml_bash() {
	local dest="$1" name="$2" extends="$3" desc="$4" mux="$5"
	local with_csv="${6:-}" without_csv="${7:-}" pkg_add="${8:-}"
	local dir item
	dir="$(dirname "${dest}")"
	mkdir -p "${dir}"

	{
		echo "# DOTS bootstrap profile — generated by ./dots"
		echo "# Data only. Apply with: ./bootstrap.sh --profile ${dest}"
		echo ""
		echo "[profile]"
		echo "name = \"${name}\""
		[[ -n ${extends} ]] && echo "extends = \"${extends}\""
		[[ -n ${desc} ]] && echo "description = \"${desc}\""
		if [[ -n ${with_csv} ]]; then
			echo "with = ["
			IFS=',' read -r -a _w <<<"${with_csv}"
			for item in "${_w[@]+"${_w[@]}"}"; do
				item="$(echo "${item}" | tr -d '[:space:]')"
				[[ -n ${item} ]] && echo "  \"${item}\","
			done
			echo "]"
		fi
		if [[ -n ${without_csv} ]]; then
			echo "without = ["
			IFS=',' read -r -a _o <<<"${without_csv}"
			for item in "${_o[@]+"${_o[@]}"}"; do
				item="$(echo "${item}" | tr -d '[:space:]')"
				[[ -n ${item} ]] && echo "  \"${item}\","
			done
			echo "]"
		fi
		if [[ -n ${pkg_add} ]]; then
			echo ""
			echo "[packages]"
			echo "add = ["
			IFS=',' read -r -a _p <<<"${pkg_add}"
			for item in "${_p[@]+"${_p[@]}"}"; do
				item="$(echo "${item}" | tr -d '[:space:]')"
				[[ -n ${item} ]] && echo "  \"${item}\","
			done
			echo "]"
		fi
		if [[ -n ${mux} ]]; then
			echo ""
			echo "[runtime]"
			echo "multiplexer = \"${mux}\""
		fi
	} >"${dest}"
}

# Write ~/.config/dots/models.toml override (sparse).
# Args: tier pull(true/false) providers_csv include_cleanup(0/1)
dots_write_models_override_bash() {
	local dest="$1" tier="$2" pull="$3" providers="${4:-}" cleanup="${5:-0}"
	mkdir -p "$(dirname "${dest}")"
	{
		echo "# DOTS model policy override — generated by ./dots"
		echo "# Does not replace configs/models.toml; merged at pull time."
		echo ""
		echo "[models]"
		[[ -n ${tier} ]] && echo "tier = \"${tier}\""
		[[ -n ${pull} ]] && echo "pull = ${pull}"
		if [[ -n ${providers} ]]; then
			echo -n "providers = ["
			local first=1 item
			IFS=',' read -r -a _pr <<<"${providers}"
			for item in "${_pr[@]+"${_pr[@]}"}"; do
				item="$(echo "${item}" | tr -d '[:space:]')"
				[[ -z ${item} ]] && continue
				[[ ${first} -eq 1 ]] || echo -n ", "
				echo -n "\"${item}\""
				first=0
			done
			echo "]"
		fi
		echo ""
		echo "[models.roles]"
		echo "general = true"
		echo "coding = true"
		echo "speech = true"
		echo "image = true"
		if [[ ${cleanup} -eq 1 ]]; then
			echo "cleanup = true"
		else
			echo "cleanup = false"
		fi
	} >"${dest}"
}
