# shellcheck shell=bash
# shellcheck disable=SC1091
# shell/runtime.sh — load profile runtime policy + machine-local overrides
# Sourced early (before exports finalize). No secrets.
#
# Precedence:
#   1. Variables already set in the process environment (preserved)
#   2. ~/.config/dots/local.sh (machine overrides; plain exports)
#   3. ~/.config/dots/runtime.env (profile policy; uses := so won't clobber)
#   4. shell/exports.sh defaults
#
# runtime.env is applied before local.sh conceptually for := defaults, then
# local.sh may export overrides. Process env set before shell start wins
# because := and ${VAR:-} do not replace non-empty values.

# Profile runtime policy (generated by bootstrap/setup)
if [ -f "${HOME}/.config/dots/runtime.env" ]; then
  # shellcheck disable=SC1090
  . "${HOME}/.config/dots/runtime.env"
fi
