# shellcheck shell=bash
# Optional modern CLI integrations shared by Bash and Zsh.
# Each block is a no-op when the tool is missing.

# zoxide — smarter cd (prefer over OMZ `z` plugin)
if command -v zoxide >/dev/null 2>&1; then
  case "${DOTS_SHELL:-}" in
    zsh)
      eval "$(zoxide init zsh)"
      ;;
    bash|*)
      eval "$(zoxide init bash)"
      ;;
  esac
fi

# direnv
if command -v direnv >/dev/null 2>&1; then
  case "${DOTS_SHELL:-}" in
    zsh)
      eval "$(direnv hook zsh)"
      ;;
    bash|*)
      eval "$(direnv hook bash)"
      ;;
  esac
fi

# atuin — local history search; do not require cloud sync
if command -v atuin >/dev/null 2>&1; then
  export ATUIN_CONFIG_DIR="${ATUIN_CONFIG_DIR:-${HOME}/.config/atuin}"
  mkdir -p "${ATUIN_CONFIG_DIR}" 2>/dev/null || true
  # Prefer local-only defaults when config is absent
  if [ ! -f "${ATUIN_CONFIG_DIR}/config.toml" ]; then
    cat >"${ATUIN_CONFIG_DIR}/config.toml" <<'EOF'
## Generated by dots — conservative local defaults (no cloud sync required)
auto_sync = false
update_check = false
style = "compact"
search_mode = "fuzzy"
filter_mode = "global"
inline_height = 20
EOF
  fi
  case "${DOTS_SHELL:-}" in
    zsh)
      eval "$(atuin init zsh --disable-up-arrow)"
      ;;
    bash|*)
      eval "$(atuin init bash --disable-up-arrow)"
      ;;
  esac
fi
