#!/usr/bin/env bash
# configure.sh — create/edit bootstrap profiles (DATA ONLY — never installs software)
#
# Interactive or noninteractive. Writes TOML consumed by bootstrap.sh.
#
# Examples:
#   ./configure.sh
#   ./configure.sh --output ~/.config/dots/profiles/studio.toml --with hermes,ollama,skills
#   ./configure.sh --from home --output ~/.config/dots/profiles/studio.toml --without cursor
#   ./configure.sh --show home
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=helpers/components.sh
source "${DIR}/helpers/components.sh"
# shellcheck source=helpers/profiles.sh
source "${DIR}/helpers/profiles.sh"

OUTPUT=""
FROM_PROFILE=""
FORCE=0
SHOW_TARGET=""
CLI_WITH=()
CLI_WITHOUT=()
SELECTED=()
PROFILE_NAME_OUT=""
DESCRIPTION=""

usage() {
	cat <<'EOF'
Usage: ./configure.sh [options]

Create or edit a bootstrap profile TOML. Never installs packages or mutates AI configs.

Options:
  --output <path>     Write profile TOML to this path
  --with <list>       Noninteractive: components to include
  --without <list>    Remove from --from baseline or --with
  --from <name|path>  Clone an existing profile as the starting set
  --name <name>       Profile name field (default: derived from output basename)
  --description <t>   Profile description
  --force             Overwrite existing output without prompting
  --show <name|path>  Show a profile (resolved) and exit
  -h, --help          Show this help

Interactive mode (no --output/--with): menu to pick target + components.

Examples:
  ./configure.sh
  ./configure.sh --output ~/.config/dots/profiles/studio.toml \
    --with hermes,herdr,ollama,skills,ai-skills,drawthings
  ./configure.sh --from home --without cursor \
    --output ~/.config/dots/profiles/no-cursor.toml
  ./configure.sh --show work
EOF
}

parse_csv_add() {
	local dest_name="$1" raw="$2" item
	local -a _parts=()
	IFS=',' read -r -a _parts <<<"${raw}"
	# Bash 3.2 + set -u: empty array expansion is unbound
	for item in "${_parts[@]+"${_parts[@]}"}"; do
		item="$(echo "${item}" | tr -d '[:space:]')"
		[[ -z ${item} ]] && continue
		eval "${dest_name}+=(\"\${item}\")"
	done
}

write_profile_toml() {
	local dest="$1"
	local name="${2:-}"
	local desc="${3:-}"
	shift 3 || true
	local comps=("$@")
	python3 - "${dest}" "${name}" "${desc}" "${comps[@]}" <<'PY'
import sys
from pathlib import Path
dest = Path(sys.argv[1])
name = sys.argv[2] or dest.stem
desc = sys.argv[3]
comps = [c for c in sys.argv[4:] if c]
dest.parent.mkdir(parents=True, exist_ok=True)
lines = [
    f'# DOTS bootstrap profile — generated by configure.sh',
    f'# Data only. Apply with: ./bootstrap.sh --profile {dest}',
    '',
    '[profile]',
    f'name = "{name}"',
    f'description = "{desc.replace(chr(34), "")}"',
    'with = [',
]
for c in comps:
    lines.append(f'  "{c}",')
lines.append(']')
lines.append('')
lines.append('open_apps = ["iTerm"]')
lines.append('')
dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"OK: wrote {dest}")
PY
}

interactive() {
	echo "DOTS profile configure (writes TOML only — no installs)"
	echo ""
	echo "Select target:"
	echo "  1) home   → configs/bootstrap/profiles/home.toml"
	echo "  2) work   → configs/bootstrap/profiles/work.toml"
	echo "  3) custom → path of your choosing"
	local choice
	read -r -p "Choice [1-3]: " choice
	case "${choice}" in
	1)
		OUTPUT="$(dots_builtin_profile_dir)/home.toml"
		PROFILE_NAME_OUT="home"
		DESCRIPTION="Personal workstation"
		;;
	2)
		OUTPUT="$(dots_builtin_profile_dir)/work.toml"
		PROFILE_NAME_OUT="work"
		DESCRIPTION="Conservative work allowlist"
		;;
	3)
		read -r -p "Output path: " OUTPUT
		OUTPUT="${OUTPUT/#\~/${HOME}}"
		PROFILE_NAME_OUT="$(basename "${OUTPUT}" .toml)"
		read -r -p "Description: " DESCRIPTION
		;;
	*)
		echo "Error: invalid choice" >&2
		exit 1
		;;
	esac

	echo ""
	echo "Select optional components (y/N for each):"
	local id label ans
	while IFS=$'\t' read -r id label; do
		[[ -z ${id} ]] && continue
		read -r -p "  [ ] ${label} (${id})? " ans
		case "${ans}" in
		y | Y | yes | YES) SELECTED+=("${id}") ;;
		esac
	done < <(
		python3 - "$(dots_components_registry_path)" <<'PY'
import sys
from pathlib import Path
import tomllib
data = tomllib.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
for c in data.get("components") or []:
    cid = (c.get("id") or "").strip()
    if not cid or c.get("omit_from_all"):
        # still offer archify explicitly
        pass
    label = (c.get("label") or cid).strip()
    if cid:
        print(f"{cid}\t{label}")
PY
	)

	echo ""
	echo "Will write:"
	echo "  ${OUTPUT}"
	echo "  components: ${SELECTED[*]:-(none)}"
	read -r -p "Save? [y/N] " ans
	case "${ans}" in
	y | Y | yes | YES) ;;
	*)
		echo "Aborted."
		exit 0
		;;
	esac
}

# --- args ---
while [[ $# -gt 0 ]]; do
	case "$1" in
	--output)
		OUTPUT="${2:-}"
		shift 2
		;;
	--output=*)
		OUTPUT="${1#*=}"
		shift
		;;
	--with)
		parse_csv_add CLI_WITH "${2:-}"
		shift 2
		;;
	--with=*)
		parse_csv_add CLI_WITH "${1#*=}"
		shift
		;;
	--without)
		parse_csv_add CLI_WITHOUT "${2:-}"
		shift 2
		;;
	--without=*)
		parse_csv_add CLI_WITHOUT "${1#*=}"
		shift
		;;
	--from)
		FROM_PROFILE="${2:-}"
		shift 2
		;;
	--from=*)
		FROM_PROFILE="${1#*=}"
		shift
		;;
	--name)
		PROFILE_NAME_OUT="${2:-}"
		shift 2
		;;
	--description)
		DESCRIPTION="${2:-}"
		shift 2
		;;
	--force)
		FORCE=1
		shift
		;;
	--show)
		SHOW_TARGET="${2:-}"
		shift 2
		;;
	--show=*)
		SHOW_TARGET="${1#*=}"
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Error: unknown option: $1" >&2
		usage >&2
		exit 1
		;;
	esac
done

if [[ -n ${SHOW_TARGET} ]]; then
	PROFILE_FILE="$(dots_resolve_profile_path "${SHOW_TARGET}")"
	dots_load_profile_file "${PROFILE_FILE}"
	CLI_WITH=()
	CLI_WITHOUT=()
	dots_compute_effective_with
	dots_show_profile_resolution
	exit 0
fi

# Noninteractive path
if [[ -n ${OUTPUT} ]] || [[ ${#CLI_WITH[@]} -gt 0 ]] || [[ -n ${FROM_PROFILE} ]]; then
	if [[ -z ${OUTPUT} ]]; then
		echo "Error: --output is required in noninteractive mode" >&2
		exit 1
	fi
	OUTPUT="${OUTPUT/#\~/${HOME}}"
	PROFILE_WITH=()
	if [[ -n ${FROM_PROFILE} ]]; then
		FROM_FILE="$(dots_resolve_profile_path "${FROM_PROFILE}")"
		dots_load_profile_file "${FROM_FILE}"
	fi
	SELECTED=()
	local_c=""
	for local_c in "${PROFILE_WITH[@]+"${PROFILE_WITH[@]}"}"; do
		SELECTED+=("${local_c}")
	done
	for local_c in "${CLI_WITH[@]+"${CLI_WITH[@]}"}"; do
		SELECTED+=("${local_c}")
	done
	# apply without + dedupe
	filtered=()
	for local_c in "${SELECTED[@]+"${SELECTED[@]}"}"; do
		dots_array_contains "${local_c}" "${CLI_WITHOUT[@]+"${CLI_WITHOUT[@]}"}" && continue
		dots_array_contains "${local_c}" "${filtered[@]+"${filtered[@]}"}" && continue
		filtered+=("${local_c}")
	done
	SELECTED=("${filtered[@]+"${filtered[@]}"}")
	if [[ ${#SELECTED[@]} -gt 0 ]]; then
		dots_validate_components "${SELECTED[@]}" || exit 1
	fi
	[[ -z ${PROFILE_NAME_OUT} ]] && PROFILE_NAME_OUT="$(basename "${OUTPUT}" .toml)"
	[[ -z ${DESCRIPTION} ]] && DESCRIPTION="Custom profile ${PROFILE_NAME_OUT}"
else
	interactive
fi

if [[ -f ${OUTPUT} ]] && [[ ${FORCE} -ne 1 ]]; then
	if [[ -t 0 ]]; then
		read -r -p "Overwrite existing ${OUTPUT}? [y/N] " ans
		case "${ans}" in
		y | Y | yes | YES) ;;
		*)
			echo "Aborted (use --force to overwrite)."
			exit 0
			;;
		esac
	else
		echo "Error: ${OUTPUT} exists (pass --force to overwrite)" >&2
		exit 1
	fi
fi

write_profile_toml "${OUTPUT}" "${PROFILE_NAME_OUT}" "${DESCRIPTION}" "${SELECTED[@]+"${SELECTED[@]}"}"
echo ""
echo "Preview:"
cat "${OUTPUT}"
echo ""
echo "Apply with: ./bootstrap.sh --profile ${OUTPUT}"
echo "configure.sh never installs software or mutates AI provider configs."
