#!/usr/bin/env bash
# configure.sh — create/edit bootstrap profiles (DATA ONLY — never installs software)
#
# Interactive or noninteractive. Writes TOML consumed by bootstrap.sh.
#
# Examples:
#   ./configure.sh
#   ./configure.sh --extends server --output ~/.config/dots/profiles/bertha.toml \
#       --packages-add infra --multiplexer tmux
#   ./configure.sh --from home --output ~/.config/dots/profiles/studio.toml --without cursor
#   ./configure.sh --show ~/.config/dots/profiles/bertha.toml
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=helpers/components.sh
source "${DIR}/helpers/components.sh"
# shellcheck source=helpers/profiles.sh
source "${DIR}/helpers/profiles.sh"

OUTPUT=""
FROM_PROFILE=""
EXTENDS=""
FORCE=0
SHOW_TARGET=""
CLI_WITH=()
CLI_WITHOUT=()
PACKAGES_ADD=()
PACKAGES_REMOVE=()
MULTIPLEXER=""
SELECTED=()
PROFILE_NAME_OUT=""
DESCRIPTION=""

usage() {
	cat <<'EOF'
Usage: ./configure.sh [options]

Create or edit a bootstrap profile TOML. Never installs packages or mutates AI configs.

Preferred customization: extend a builtin preset into ~/.config/dots/profiles/.

Options:
  --output <path>       Write profile TOML to this path
  --extends <name|path> Inherit from a builtin/custom profile (writes extends=)
  --from <name|path>    Clone resolved components from a profile (no extends=)
  --with <list>         Components to include (CSV)
  --without <list>      Components to exclude (CSV)
  --packages-add <list> Package groups to add (CSV)
  --packages-remove <l> Package groups to remove (CSV)
  --multiplexer <m>     Runtime multiplexer: tmux|herdr|none
  --name <name>         Profile name field (default: output basename)
  --description <t>     Profile description
  --force               Overwrite existing output without prompting
  --show <name|path>    Show resolved profile and exit
  -h, --help            Show this help

Examples:
  ./configure.sh --extends server --output ~/.config/dots/profiles/bertha.toml \
    --name bertha --packages-add infra --multiplexer herdr
  ./configure.sh --extends work --output ~/.config/dots/profiles/corp-work.toml \
    --with images --packages-add infra
  ./configure.sh --extends home --output ~/.config/dots/profiles/home-studio.toml \
    --without cursor --multiplexer tmux
  ./configure.sh --show ~/.config/dots/profiles/bertha.toml
EOF
}

parse_csv_add() {
	local dest_name="$1" raw="$2" item
	local -a _parts=()
	IFS=',' read -r -a _parts <<<"${raw}"
	# Bash 3.2 + set -u: empty array expansion is unbound
	for item in "${_parts[@]+"${_parts[@]}"}"; do
		item="$(echo "${item}" | tr -d '[:space:]')"
		[[ -z ${item} ]] && continue
		eval "${dest_name}+=(\"\${item}\")"
	done
}

write_profile_toml() {
	local dest="$1"
	python3 - "$dest" "${PROFILE_NAME_OUT}" "${DESCRIPTION}" "${EXTENDS}" "${MULTIPLEXER}" \
		"${CLI_WITH[*]:-}" "${CLI_WITHOUT[*]:-}" "${PACKAGES_ADD[*]:-}" "${PACKAGES_REMOVE[*]:-}" <<'PY'
import sys
from pathlib import Path

dest = Path(sys.argv[1])
name = sys.argv[2] or dest.stem
desc = (sys.argv[3] or "").replace('"', "")
extends = sys.argv[4].strip()
multiplexer = sys.argv[5].strip()
with_list = [x for x in sys.argv[6].split() if x]
without_list = [x for x in sys.argv[7].split() if x]
pkg_add = [x for x in sys.argv[8].split() if x]
pkg_remove = [x for x in sys.argv[9].split() if x]

dest.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "# DOTS bootstrap profile — generated by configure.sh",
    f"# Data only. Apply with: ./bootstrap.sh --profile {dest}",
    "",
    "[profile]",
    f'name = "{name}"',
]
if extends:
    lines.append(f'extends = "{extends}"')
if desc:
    lines.append(f'description = "{desc}"')
if with_list:
    lines.append("with = [")
    for c in with_list:
        lines.append(f'  "{c}",')
    lines.append("]")
if without_list:
    lines.append("without = [")
    for c in without_list:
        lines.append(f'  "{c}",')
    lines.append("]")

if pkg_add or pkg_remove:
    lines.append("")
    lines.append("[packages]")
    if pkg_add:
        lines.append("add = [" + ", ".join(f'"{g}"' for g in pkg_add) + "]")
    if pkg_remove:
        lines.append("remove = [" + ", ".join(f'"{g}"' for g in pkg_remove) + "]")

if multiplexer:
    lines.append("")
    lines.append("[runtime]")
    lines.append(f'multiplexer = "{multiplexer}"')

dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"OK: wrote {dest}")
PY
}

interactive() {
	echo "DOTS profile configure (writes TOML only — no installs)"
	echo ""
	echo "Select target:"
	echo "  1) custom extending server → ~/.config/dots/profiles/<name>.toml"
	echo "  2) custom extending home"
	echo "  3) custom extending work"
	echo "  4) edit repository home.toml (discouraged)"
	echo "  5) edit repository work.toml (discouraged)"
	local choice
	read -r -p "Choice [1-5]: " choice
	case "${choice}" in
	1)
		EXTENDS="server"
		read -r -p "Profile name [bertha]: " PROFILE_NAME_OUT
		PROFILE_NAME_OUT="${PROFILE_NAME_OUT:-bertha}"
		OUTPUT="${HOME}/.config/dots/profiles/${PROFILE_NAME_OUT}.toml"
		DESCRIPTION="Custom server profile"
		;;
	2)
		EXTENDS="home"
		read -r -p "Profile name [home-custom]: " PROFILE_NAME_OUT
		PROFILE_NAME_OUT="${PROFILE_NAME_OUT:-home-custom}"
		OUTPUT="${HOME}/.config/dots/profiles/${PROFILE_NAME_OUT}.toml"
		DESCRIPTION="Custom home profile"
		;;
	3)
		EXTENDS="work"
		read -r -p "Profile name [work-custom]: " PROFILE_NAME_OUT
		PROFILE_NAME_OUT="${PROFILE_NAME_OUT:-work-custom}"
		OUTPUT="${HOME}/.config/dots/profiles/${PROFILE_NAME_OUT}.toml"
		DESCRIPTION="Custom work profile"
		;;
	4)
		OUTPUT="$(dots_builtin_profile_dir)/home.toml"
		PROFILE_NAME_OUT="home"
		DESCRIPTION="Personal workstation"
		;;
	5)
		OUTPUT="$(dots_builtin_profile_dir)/work.toml"
		PROFILE_NAME_OUT="work"
		DESCRIPTION="Conservative work allowlist"
		;;
	*)
		echo "Error: invalid choice" >&2
		exit 1
		;;
	esac

	read -r -p "Automatic multiplexer [tmux/herdr/none, blank=inherit]: " MULTIPLEXER

	echo ""
	echo "Select optional components to ADD (y/N for each):"
	local id label ans
	while IFS=$'\t' read -r id label; do
		[[ -z ${id} ]] && continue
		read -r -p "  [ ] ${label} (${id})? " ans
		case "${ans}" in
		y | Y | yes | YES) CLI_WITH+=("${id}") ;;
		esac
	done < <(
		python3 - "$(dots_components_registry_path)" <<'PY'
import sys
from pathlib import Path
import tomllib
data = tomllib.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
for c in data.get("components") or []:
    cid = (c.get("id") or "").strip()
    label = (c.get("label") or cid).strip()
    if cid:
        print(f"{cid}\t{label}")
PY
	)

	echo ""
	echo "Select supergroups to ADD (y/N for each):"
	while IFS=$'\t' read -r id label; do
		[[ -z ${id} ]] && continue
		read -r -p "  [ ] ${label} (${id})? " ans
		case "${ans}" in
		y | Y | yes | YES) CLI_WITH+=("${id}") ;;
		esac
	done < <(
		python3 - "$(dots_components_registry_path)" <<'PY'
import sys
from pathlib import Path
import tomllib
data = tomllib.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
for g in data.get("supergroups") or []:
    gid = (g.get("id") or "").strip()
    label = (g.get("label") or gid).strip()
    desc = (g.get("description") or "").strip()
    if gid:
        print("%s\t%s%s" % (gid, label, (" — " + desc) if desc else ""))
PY
	)

	echo ""
	echo "Will write:"
	echo "  ${OUTPUT}"
	[[ -n ${EXTENDS} ]] && echo "  extends: ${EXTENDS}"
	echo "  with: ${CLI_WITH[*]:-(none)}"
	[[ -n ${MULTIPLEXER} ]] && echo "  multiplexer: ${MULTIPLEXER}"
	read -r -p "Save? [y/N] " ans
	case "${ans}" in
	y | Y | yes | YES) ;;
	*)
		echo "Aborted."
		exit 0
		;;
	esac
}

# --- args ---
while [[ $# -gt 0 ]]; do
	case "$1" in
	--output)
		OUTPUT="${2:-}"
		shift 2
		;;
	--output=*)
		OUTPUT="${1#*=}"
		shift
		;;
	--with)
		parse_csv_add CLI_WITH "${2:-}"
		shift 2
		;;
	--with=*)
		parse_csv_add CLI_WITH "${1#*=}"
		shift
		;;
	--without)
		parse_csv_add CLI_WITHOUT "${2:-}"
		shift 2
		;;
	--without=*)
		parse_csv_add CLI_WITHOUT "${1#*=}"
		shift
		;;
	--packages-add)
		parse_csv_add PACKAGES_ADD "${2:-}"
		shift 2
		;;
	--packages-add=*)
		parse_csv_add PACKAGES_ADD "${1#*=}"
		shift
		;;
	--packages-remove)
		parse_csv_add PACKAGES_REMOVE "${2:-}"
		shift 2
		;;
	--packages-remove=*)
		parse_csv_add PACKAGES_REMOVE "${1#*=}"
		shift
		;;
	--multiplexer)
		MULTIPLEXER="${2:-}"
		shift 2
		;;
	--multiplexer=*)
		MULTIPLEXER="${1#*=}"
		shift
		;;
	--extends)
		EXTENDS="${2:-}"
		shift 2
		;;
	--extends=*)
		EXTENDS="${1#*=}"
		shift
		;;
	--from)
		FROM_PROFILE="${2:-}"
		shift 2
		;;
	--from=*)
		FROM_PROFILE="${1#*=}"
		shift
		;;
	--name)
		PROFILE_NAME_OUT="${2:-}"
		shift 2
		;;
	--description)
		DESCRIPTION="${2:-}"
		shift 2
		;;
	--force)
		FORCE=1
		shift
		;;
	--show)
		SHOW_TARGET="${2:-}"
		shift 2
		;;
	--show=*)
		SHOW_TARGET="${1#*=}"
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Error: unknown option: $1" >&2
		usage >&2
		exit 1
		;;
	esac
done

if [[ -n ${SHOW_TARGET} ]]; then
	PROFILE_FILE="$(dots_resolve_profile_path "${SHOW_TARGET}")"
	dots_load_profile_file "${PROFILE_FILE}"
	CLI_WITH=()
	CLI_WITHOUT=()
	dots_compute_effective_with
	dots_show_profile_resolution
	exit 0
fi

# Noninteractive path
if [[ -n ${OUTPUT} ]] || [[ ${#CLI_WITH[@]} -gt 0 ]] || [[ -n ${FROM_PROFILE} ]] || [[ -n ${EXTENDS} ]]; then
	if [[ -z ${OUTPUT} ]]; then
		echo "Error: --output is required in noninteractive mode" >&2
		exit 1
	fi
	OUTPUT="${OUTPUT/#\~/${HOME}}"
	if [[ -n ${FROM_PROFILE} && -z ${EXTENDS} ]]; then
		# Legacy clone: materialize resolved with= list (no extends)
		FROM_FILE="$(dots_resolve_profile_path "${FROM_PROFILE}")"
		dots_load_profile_file "${FROM_FILE}" >/dev/null
		CLI_WITH=("${PROFILE_WITH[@]+"${PROFILE_WITH[@]}"}" "${CLI_WITH[@]+"${CLI_WITH[@]}"}")
	fi
	if [[ ${#CLI_WITH[@]} -gt 0 ]]; then
		dots_validate_selectors "${CLI_WITH[@]}" || exit 1
	fi
	if [[ ${#CLI_WITHOUT[@]} -gt 0 ]]; then
		dots_validate_selectors "${CLI_WITHOUT[@]}" || exit 1
	fi
	if [[ ${#PACKAGES_ADD[@]} -gt 0 || ${#PACKAGES_REMOVE[@]} -gt 0 ]]; then
		# shellcheck source=helpers/packages.sh
		source "${DIR}/helpers/packages.sh"
		dots_validate_package_groups "${PACKAGES_ADD[@]+"${PACKAGES_ADD[@]}"}" "${PACKAGES_REMOVE[@]+"${PACKAGES_REMOVE[@]}"}" || exit 1
	fi
	if [[ -n ${MULTIPLEXER} ]]; then
		case "${MULTIPLEXER}" in
		tmux | herdr | none) ;;
		*)
			echo "Error: invalid multiplexer '${MULTIPLEXER}' (tmux|herdr|none)" >&2
			exit 1
			;;
		esac
	fi
	[[ -z ${PROFILE_NAME_OUT} ]] && PROFILE_NAME_OUT="$(basename "${OUTPUT}" .toml)"
	[[ -z ${DESCRIPTION} ]] && DESCRIPTION="Custom profile ${PROFILE_NAME_OUT}"
else
	interactive
fi

if [[ -f ${OUTPUT} ]] && [[ ${FORCE} -ne 1 ]]; then
	if [[ -t 0 ]]; then
		read -r -p "Overwrite existing ${OUTPUT}? [y/N] " ans
		case "${ans}" in
		y | Y | yes | YES) ;;
		*)
			echo "Aborted (use --force to overwrite)."
			exit 0
			;;
		esac
	else
		echo "Error: ${OUTPUT} exists (pass --force to overwrite)" >&2
		exit 1
	fi
fi

write_profile_toml "${OUTPUT}"
echo ""
echo "Preview:"
cat "${OUTPUT}"
echo ""
echo "Apply with: ./bootstrap.sh --profile ${OUTPUT}"
echo "Preview:    ./bootstrap.sh --profile ${OUTPUT} --show"
echo "configure.sh never installs software or mutates AI provider configs."
