-- Generated by scripts/generate_lsp_nvim.py; do not edit.
-- Authority: configs/lsp/servers.toml
return {
  rust_analyzer = {
    filetypes = { "rust" },
  },
  basedpyright = {
    filetypes = { "python" },
  },
  gopls = {
    filetypes = { "go", "gomod", "gowork", "gotmpl" },
  },
  bashls = {
    cmd = { "bash-language-server", "start" },
    filetypes = { "sh", "bash", "zsh" },
  },
  yamlls = {
    cmd = { "yaml-language-server", "--stdio" },
    filetypes = { "yaml", "yaml.docker-compose", "yaml.github-actions" },
    settings = {
      yaml = {
        validate = true,
        completion = true,
        hover = true,
        schemaStore = {
          enable = true,
        },
        schemas = {
          ["https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json"] = { "docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml" },
          ["https://json.schemastore.org/github-workflow.json"] = { ".github/workflows/*.yml", ".github/workflows/*.yaml" },
          kubernetes = { "k8s/*.yml", "k8s/*.yaml", "kubernetes/*.yml", "kubernetes/*.yaml" },
        },
      },
    },
  },
  jsonls = {
    cmd = { "vscode-json-language-server", "--stdio" },
    filetypes = { "json", "jsonc" },
  },
  lua_ls = {
    filetypes = { "lua" },
    settings = {
      Lua = {
        diagnostics = {
          globals = { "vim" },
        },
        workspace = {
          checkThirdParty = false,
          library = { vim.env.VIMRUNTIME },
        },
      },
    },
  },
  markdown_oxide = {
    filetypes = { "markdown", "markdown.mdx" },
  },
  taplo = {
    filetypes = { "toml" },
  },
  terraformls = {
    filetypes = { "terraform", "terraform-vars", "hcl" },
  },
  dockerls = {
    cmd = { "docker-langserver", "--stdio" },
    filetypes = { "dockerfile" },
  },
  r_language_server = {
    cmd = { "R", "--no-echo", "-e", "languageserver::run()" },
    filetypes = { "r", "rmd" },
  },
}
