# brew/groups/modern.Brewfile — shared ergonomic CLI tools
brew "eza"
brew "bat"
brew "zoxide"
brew "direnv"
brew "atuin"
brew "lazygit"
brew "htop"
brew "btop"
brew "yq"
brew "uv"
brew "gh"
brew "just"
brew "git-delta"
brew "git-lfs"
brew "moreutils"
brew "fastfetch"
brew "tree"
brew "vim"
# Terminal Markdown previewer (binary: leaf)
brew "leaf-markdown-viewer"
