#!/usr/bin/env python3
"""Generate Neovim's server table from configs/lsp/servers.toml."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "configs/lsp/servers.toml"
OUTPUT = ROOT / "configs/nvim/lua/config/lsp_servers.lua"


def lua(value: object, indent: int = 0) -> str:
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        if value == "__DOTS_VIMRUNTIME__":
            return "vim.env.VIMRUNTIME"
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "{ " + ", ".join(lua(item, indent + 2) for item in value) + " }"
    if isinstance(value, dict):
        if not value:
            return "{}"
        pad = " " * indent
        child = " " * (indent + 2)
        rows = []
        for key, item in value.items():
            if key.replace("_", "a").isalnum() and not key[0].isdigit():
                rendered_key = key
            else:
                rendered_key = f"[{lua(key)}]"
            rows.append(f"{child}{rendered_key} = {lua(item, indent + 2)},")
        return "{\n" + "\n".join(rows) + f"\n{pad}}}"
    raise TypeError(f"unsupported Lua value: {type(value)!r}")


def render() -> str:
    data = tomllib.loads(REGISTRY.read_text(encoding="utf-8"))
    rows = [
        "-- Generated by scripts/generate_lsp_nvim.py; do not edit.",
        "-- Authority: configs/lsp/servers.toml",
        "return {",
    ]
    for server in data.get("servers", []):
        name = server["nvim"]
        options = server.get("nvim_config", {})
        rows.append(f"  {name} = {lua(options, 2)},")
    rows.append("}")
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
