# Zsh history — intentional large persistent history
#
# Equivalents requested:
#   APPEND_HISTORY INC_APPEND_HISTORY SHARE_HISTORY
#   HIST_IGNORE_DUPS HIST_IGNORE_ALL_DUPS HIST_FIND_NO_DUPS
#   HIST_REDUCE_BLANKS HIST_SAVE_NO_DUPS
# Plus space-prefixed commands excluded via HIST_IGNORE_SPACE.

HISTFILE="${DOTS_HISTFILE:-${HOME}/.zsh_history}"
HISTSIZE=100000
SAVEHIST=100000

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
